baseURL = "https://benfielding74.github.io/"
languageCode = "en-us"
title = "Ben Fielding - Apprenticeship Portfolio"
theme = "PaperMod"

[Params.editPost] 
        URL = "https://github.com/benfielding74/apprentice-portfolio/tree/main/content"
        Text = "Suggest Changes" # edit text
        appendFilePath = true # to append file path to Edit link
        
[menu]

[[menu.main]]

  identifier = 'contents'
  name = 'contents'
  pre = "<i class='fa fa-heart'></i>"
  url = '/contents/'
  weight = -110

[markup.goldmark.renderer]
  unsafe = true
